import { useEffect, useMemo, useReducer, useState } from 'react'
import { initialModel, reduce, reduceMany, clearModel, type Instance, type Model } from './state.js'
import type { MFEvent, RuntimeMessage } from '../shared/protocol.js'

type Action =
  | { type: 'events'; events: MFEvent[] }
  | { type: 'clear' }

function modelReducer(state: Model, action: Action): Model {
  switch (action.type) {
    case 'events':
      return reduceMany(state, action.events)
    case 'clear':
      return clearModel()
  }
}

// Per-mode tooltip text — shown on hover of the badge in the list and detail.
const MODE_TOOLTIPS: Record<string, string> = {
  bridge: '<MFBridge> — remote mounted via register() returned by createMFEntry',
  lazy: '<MFBridgeLazy> — wrapper that tracks the load() lifecycle (start/retry/ok/error). Resolves into a BRIDGE instance when the remote loads.',
  hydrated: '<MFBridgeHydrated> — binds the host to a DOM container that already has SSR-rendered markup',
  'ssr-url': '<MFBridgeSSR url=...> — fetched HTML fragment from a URL',
  'ssr-loader': '<MFBridgeSSR loader=...> — fragment loaded through a Module Federation loader',
  'remote-entry': 'createMFEntry() called inside a remote (reserved; not yet emitted)',
  'remote-define-entry': 'defineMFEntry() called inside a remote (reserved; not yet emitted)',
  'remote-hydrate': 'hydrateWithBridge() called inside a remote (reserved; not yet emitted)',
  fetch: 'Synthetic instance representing the HTTP fetch of an SSR fragment HTML or loader.js',
}

const STATUS_TOOLTIPS: Record<string, string> = {
  loading: 'Initial state — waiting for register() / fragment / hydration to complete',
  mounted: 'Live — currently rendered in the DOM and listening for events',
  unmounted: 'Removed from the DOM. Kept in the list for inspection.',
  error: 'Failed (load:error, fetch:error, or render-time exception)',
}

// Namespaces shaped `mfbridge-N` / `mfssr-N` are auto-generated by the
// package when the host doesn't pass `namespace` explicitly. Mark them so
// they don't read like deliberate channel names.
const AUTO_NAMESPACE_RE = /^mf(bridge|ssr)-\d+$/

function isAutoNamespace(ns: string | undefined): boolean {
  return !!ns && AUTO_NAMESPACE_RE.test(ns)
}

const AUTO_NS_TOOLTIP =
  'Auto-generated. The host did not pass `namespace` to the component, so the package created an internal id for the bus channel.\n\nFor multi-MF pages, prefer explicit names (e.g. namespace="checkout") — they are stable across remounts and easier to read in DevTools.'

const CONN_TOOLTIPS: Record<'connected' | 'reconnecting' | 'disconnected', string> = {
  connected: 'Connected to background service worker — events are streaming live.',
  reconnecting: 'Service worker went idle (Manifest V3 ~30s timeout). Reconnecting…',
  disconnected: 'Not connected. Open DevTools on a tab that has mf-bridge / mf-ssr loaded.',
}

// Per-event-kind tooltips (used on filter chips, event-log rows, and the help popover).
const KIND_TOOLTIPS: Record<string, string> = {
  mount: 'Component mounted (or, for SSR, fragment is in the DOM and bus is bound).',
  unmount: 'Component left the DOM. May be a real navigation, or a StrictMode dev test cycle.',
  props: 'Host streamed new props to the remote. The diff shows which keys changed.',
  event: 'Bus event between host and remote. Direction is host→remote (command) or remote→host (notification).',
  load: 'Lazy-load lifecycle for <MFBridgeLazy>: start → ok / retry / error.',
  fetch: 'HTTP fetch lifecycle for an SSR fragment: start → ok / retry / error.',
}

const DIRECTION_TOOLTIPS = {
  'host->remote': 'Host invoked cmdRef.current(type, payload) — command to the remote.',
  'remote->host': 'Remote called emit(type, payload) — notification to the host.',
} as const

const DIFF_OP_TOOLTIPS = {
  add: 'Key added in this update — was not present in the previous props.',
  remove: 'Key removed in this update — present before, gone now.',
  change: 'Key value changed (shallow comparison; arrays/objects via JSON-equal).',
} as const

export function App(): React.JSX.Element {
  const [model, dispatch] = useReducer(modelReducer, initialModel)
  const [selected, setSelected] = useState<string | null>(null)
  const [paused, setPaused] = useState(false)
  const [hideUnmounted, setHideUnmounted] = useState(true)
  const [connState, setConnState] = useState<'connected' | 'reconnecting' | 'disconnected'>('disconnected')
  const [helpOpen, setHelpOpen] = useState(false)
  const pausedRef = useBufferedPause(paused, dispatch)

  // Wire up the long-lived port to the background service worker. MV3 service
  // workers can be evicted after ~30s of inactivity even with a port open; in
  // that case the port disconnects and any subsequent events from the page
  // are dropped on the floor. Reconnect on disconnect with a small delay, and
  // re-pull the content-bridge buffer so we don't miss anything that arrived
  // while the worker was down. The reducer dedupes identical events.
  useEffect(() => {
    const tabId = chrome.devtools.inspectedWindow.tabId
    let port: chrome.runtime.Port | null = null
    let cancelled = false
    let reconnectTimer: ReturnType<typeof setTimeout> | null = null

    const onMessage = (msg: RuntimeMessage): void => {
      if (msg.type !== 'mf-events') return
      if (pausedRef.current) {
        pausedRef.buffer.push(...msg.events)
        return
      }
      dispatch({ type: 'events', events: msg.events })
    }

    const pullBuffered = (): void => {
      void chrome.tabs.sendMessage<RuntimeMessage, { events?: MFEvent[] }>(
        tabId,
        { type: 'mf-panel-ready', tabId },
      ).then((res) => {
        if (cancelled) return
        if (res?.events?.length) dispatch({ type: 'events', events: res.events })
      }).catch(() => {
        // No content script on this tab (chrome:// page, no permissions, etc.).
      })
    }

    const connect = (): void => {
      if (cancelled) return
      port = chrome.runtime.connect({ name: `mf-devtools:${tabId}` })
      port.onMessage.addListener(onMessage)
      setConnState('connected')
      port.onDisconnect.addListener(() => {
        port = null
        if (cancelled) return
        setConnState('reconnecting')
        // Worker likely went idle. Reconnect after a short backoff; the
        // service worker will respawn on the new connect call.
        reconnectTimer = setTimeout(connect, 500)
      })
      pullBuffered()
    }

    connect()

    return () => {
      cancelled = true
      if (reconnectTimer !== null) clearTimeout(reconnectTimer)
      port?.disconnect()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const items = useMemo(() => model.order.map((id) => model.byId[id]).filter(Boolean), [model])
  const visibleItems = useMemo(
    () => (hideUnmounted ? items.filter((i) => i.status !== 'unmounted') : items),
    [items, hideUnmounted],
  )
  const groups = useMemo(() => groupByNamespace(visibleItems), [visibleItems])
  const liveCount = items.filter((i) => i.status !== 'unmounted').length
  const totalCount = items.length
  const selectedInstance = selected ? model.byId[selected] : null

  return (
    <div className="layout">
      <div className="toolbar">
        <button
          onClick={() => {
            dispatch({ type: 'clear' })
            setSelected(null)
            const tabId = chrome.devtools.inspectedWindow.tabId
            void chrome.tabs.sendMessage(tabId, { type: 'mf-clear', tabId }).catch(() => {})
          }}
          title="Clear all captured instances and events. Re-mount components or reload the page to see them again."
        >
          Clear
        </button>
        <button
          onClick={() => setPaused((p) => !p)}
          title={paused
            ? 'Currently paused — incoming events are buffered and will be flushed on resume.'
            : 'Pause stops the panel from processing incoming events. The page keeps emitting; events queue up and arrive in order when you resume.'}
        >
          {paused ? 'Resume' : 'Pause'}
        </button>
        <button
          onClick={() => exportEventsJson(items)}
          disabled={items.length === 0}
          title="Download a JSON dump of every captured instance and its event log. Useful for bug reports."
        >
          Export
        </button>
        <label className="toggle" title="StrictMode in dev double-mounts every effect, so the list fills with twin UNMOUNTED entries. Hiding them shows only what's currently in the DOM.">
          <input
            type="checkbox"
            checked={hideUnmounted}
            onChange={(e) => setHideUnmounted(e.target.checked)}
          />
          Hide unmounted
        </label>
        <span
          className="status"
          title={hideUnmounted
            ? `${liveCount} live, ${totalCount - liveCount} hidden as unmounted (${totalCount} total).`
            : `${totalCount} total instances captured this session (Clear to reset).`}
        >
          <span
            className={`conn-dot conn-${connState}`}
            title={CONN_TOOLTIPS[connState]}
            aria-label={`Connection: ${connState}`}
          />
          {hideUnmounted
            ? `${liveCount} of ${totalCount} ${totalCount === 1 ? 'instance' : 'instances'}`
            : `${totalCount} ${totalCount === 1 ? 'instance' : 'instances'}`}
        </span>
        <button
          className="help-btn"
          onClick={() => setHelpOpen((o) => !o)}
          title="What do these badges and event kinds mean? Cheat sheet."
          aria-label="Help"
        >
          ?
        </button>
      </div>
      {helpOpen && <HelpPopover onClose={() => setHelpOpen(false)} />}

      <div className="list">
        {visibleItems.length === 0 ? (
          <div className="empty">
            {totalCount === 0 ? (
              <>
                <strong>No microfrontends detected yet.</strong>
                <br />
                Open a page that mounts <code>&lt;MFBridge&gt;</code>, <code>&lt;MFBridgeLazy&gt;</code>,
                <code> &lt;MFBridgeHydrated&gt;</code>, or <code>&lt;MFBridgeSSR&gt;</code>.
                <br /><br />
                Events fire only in development builds (the emitter is dead-code-eliminated in production).
              </>
            ) : (
              <>
                <strong>All instances are unmounted.</strong>
                <br />
                Uncheck "Hide unmounted" above to see history.
              </>
            )}
          </div>
        ) : (
          groups.map((group) => (
            <div key={group.namespace} className="group">
              {group.instances.map((inst, idx) => (
                <ListRow
                  key={inst.id}
                  inst={inst}
                  selected={inst.id === selected}
                  onSelect={() => setSelected(inst.id)}
                  isChild={idx > 0 && group.instances.length > 1}
                  showNamespace={idx === 0}
                />
              ))}
            </div>
          ))
        )}
      </div>

      <div className="detail">
        {selectedInstance ? (
          <Detail inst={selectedInstance} />
        ) : (
          <div className="empty-detail">Select an instance to inspect.</div>
        )}
      </div>
    </div>
  )
}

function HelpPopover({ onClose }: { onClose: () => void }): React.JSX.Element {
  return (
    <div className="help-overlay" onClick={onClose}>
      <div className="help-popover" onClick={(e) => e.stopPropagation()} role="dialog" aria-label="Help">
        <div className="help-head">
          <h3>What this panel shows</h3>
          <button onClick={onClose} aria-label="Close" className="close-btn">×</button>
        </div>

        <p>
          Every <code>&lt;MFBridge&gt;</code>, <code>&lt;MFBridgeLazy&gt;</code>, <code>&lt;MFBridgeHydrated&gt;</code>{' '}
          and <code>&lt;MFBridgeSSR&gt;</code> instance on the page emits lifecycle events into this panel.
          Events are captured only in development builds.
        </p>

        <h4>Modes (color of the badge)</h4>
        <dl className="legend">
          <dt><span className="badge badge-lazy">lazy</span></dt>
          <dd>{MODE_TOOLTIPS.lazy}</dd>
          <dt><span className="badge badge-bridge">bridge</span></dt>
          <dd>{MODE_TOOLTIPS.bridge}</dd>
          <dt><span className="badge badge-hydrated">hydrated</span></dt>
          <dd>{MODE_TOOLTIPS.hydrated}</dd>
          <dt><span className="badge badge-ssr-url">ssr-url</span></dt>
          <dd>{MODE_TOOLTIPS['ssr-url']}</dd>
          <dt><span className="badge badge-ssr-loader">ssr-loader</span></dt>
          <dd>{MODE_TOOLTIPS['ssr-loader']}</dd>
          <dt><span className="badge badge-ssr-url">fetch</span></dt>
          <dd>{MODE_TOOLTIPS.fetch}</dd>
        </dl>

        <h4>Event kinds</h4>
        <dl className="legend">
          <dt><code>mount</code></dt><dd>{KIND_TOOLTIPS.mount}</dd>
          <dt><code>unmount</code></dt><dd>{KIND_TOOLTIPS.unmount}</dd>
          <dt><code>props</code></dt><dd>{KIND_TOOLTIPS.props}</dd>
          <dt><code>event</code></dt><dd>{KIND_TOOLTIPS.event}</dd>
          <dt><code>load</code></dt><dd>{KIND_TOOLTIPS.load}</dd>
          <dt><code>fetch</code></dt><dd>{KIND_TOOLTIPS.fetch}</dd>
        </dl>

        <h4>Why so many UNMOUNTED rows in dev?</h4>
        <p>
          React <strong>StrictMode</strong> in development double-invokes every effect (mount → cleanup → mount)
          to surface bugs. Each pair shows up here as a real instance + a UNMOUNTED twin.
          Toggle <em>Hide unmounted</em> in the toolbar to filter them out. Production builds don't have this.
        </p>

        <h4>Why <code>(auto)</code> next to a namespace?</h4>
        <p>
          The host did not pass a <code>namespace</code> prop, so the package generated <code>mfbridge-N</code>{' '}
          / <code>mfssr-N</code> for the bus channel. For multi-MF pages, prefer explicit names — they
          are stable across remounts and easier to read.
        </p>

        <h4>Why a LAZY and a BRIDGE for the same component?</h4>
        <p>
          One <code>&lt;MFBridgeLazy&gt;</code> in JSX produces two records: the outer wrapper (LAZY,
          load lifecycle) and the inner real mount (BRIDGE, props/events). They share the same namespace
          and are grouped together in the list.
        </p>
      </div>
    </div>
  )
}

interface ListRowProps {
  inst: Instance
  selected: boolean
  onSelect: () => void
  /** True when this row is a sibling under the same namespace (not the first one shown). */
  isChild?: boolean
  /** Show the namespace label (only on the first row of a namespace group). */
  showNamespace?: boolean
}

function ListRow({ inst, selected, onSelect, isChild, showNamespace }: ListRowProps): React.JSX.Element {
  const nsLabel = inst.namespace || '(no namespace)'
  const isAuto = isAutoNamespace(inst.namespace)
  const nsTooltip = isAuto
    ? AUTO_NS_TOOLTIP
    : inst.namespace
      ? `Bus channel — host and remote use the same namespace to exchange events.`
      : `No namespace passed by the host. The package generated an internal id for the bus channel.`

  // Flash the row briefly when a new event arrives on this instance, so the
  // user can see at a glance which one is "active right now".
  const flashing = useFlashOnEvent(inst.events.length, inst.events[inst.events.length - 1]?.ts)

  return (
    <div
      className={`list-item${selected ? ' selected' : ''}${isChild ? ' child' : ''}${flashing ? ' flash' : ''}`}
      onClick={onSelect}
    >
      {showNamespace && (
        <div className="ns" title={nsTooltip}>
          {nsLabel}
          {isAuto && <span className="ns-auto" title={AUTO_NS_TOOLTIP}> (auto)</span>}
        </div>
      )}
      <div className="meta">
        <span
          className={`badge badge-${inst.mode === 'fetch' ? 'ssr-url' : inst.mode}`}
          title={MODE_TOOLTIPS[inst.mode] ?? inst.mode}
        >
          {inst.mode}
        </span>
        {inst.status === 'unmounted' && (
          <span className="badge badge-unmounted" title={STATUS_TOOLTIPS.unmounted}>unmounted</span>
        )}
        {inst.status === 'error' && (
          <span className="badge badge-error" title={STATUS_TOOLTIPS.error}>error</span>
        )}
        {inst.shadowDom && (
          <span className="badge badge-bridge" title="Rendered inside Shadow DOM (CSS-isolated)">shadow</span>
        )}
        <span title={`Instance id: ${inst.id}`}>{inst.id}</span>
      </div>
      {inst.url && (
        <div className="meta" title={inst.url}>
          {truncate(inst.url, 40)}
        </div>
      )}
    </div>
  )
}

interface NamespaceGroup {
  namespace: string
  instances: Instance[]
}

/**
 * Group instances by namespace so a paired LAZY+BRIDGE (the same MFBridgeLazy
 * spawning an inner MFBridge) shows up as a single visual group rather than
 * two unrelated rows. Within a group, sort by mode priority so LAZY (the
 * outer wrapper) renders first, with the resolved BRIDGE underneath it.
 */
function groupByNamespace(items: Instance[]): NamespaceGroup[] {
  const orderedNs: string[] = []
  const buckets = new Map<string, Instance[]>()
  for (const inst of items) {
    const key = inst.namespace || `__nons__:${inst.id}` // fetch and unnamed instances each in their own group
    if (!buckets.has(key)) {
      buckets.set(key, [])
      orderedNs.push(key)
    }
    buckets.get(key)!.push(inst)
  }
  // Sort within each group: lazy → bridge → hydrated → ssr-* → fetch → others.
  const modePriority: Record<string, number> = {
    lazy: 0, bridge: 1, hydrated: 2,
    'ssr-url': 3, 'ssr-loader': 4, fetch: 5,
  }
  for (const arr of buckets.values()) {
    arr.sort((a, b) => (modePriority[a.mode] ?? 99) - (modePriority[b.mode] ?? 99))
  }
  return orderedNs.map((key) => ({
    namespace: key.startsWith('__nons__:') ? '(no namespace)' : key,
    instances: buckets.get(key)!,
  }))
}

const ALL_KINDS: ReadonlyArray<MFEvent['kind']> = ['mount', 'unmount', 'props', 'event', 'load', 'fetch']

function Detail({ inst }: { inst: Instance }): React.JSX.Element {
  const lifetime = useLifetime(inst)
  const eventBreakdown = useMemo(() => summarizeEventKinds(inst.events), [inst.events])
  const [enabledKinds, setEnabledKinds] = useState<Set<MFEvent['kind']>>(new Set(ALL_KINDS))
  const filteredEvents = useMemo(
    () => inst.events.filter((e) => enabledKinds.has(e.kind)),
    [inst.events, enabledKinds],
  )
  const toggleKind = (k: MFEvent['kind']) => {
    setEnabledKinds((prev) => {
      const next = new Set(prev)
      next.has(k) ? next.delete(k) : next.add(k)
      return next
    })
  }
  // Counts per kind for the filter chips — only show kinds that exist on this instance.
  const kindCounts = useMemo(() => {
    const c: Record<string, number> = {}
    for (const e of inst.events) c[e.kind] = (c[e.kind] ?? 0) + 1
    return c
  }, [inst.events])
  return (
    <>
      <h2>
        <span
          title={
            isAutoNamespace(inst.namespace)
              ? AUTO_NS_TOOLTIP
              : inst.namespace
                ? 'Bus channel for host↔remote events'
                : 'No namespace prop — internal id used'
          }
        >
          {inst.namespace || '(no namespace)'}
        </span>
        {isAutoNamespace(inst.namespace) && (
          <span className="ns-auto" title={AUTO_NS_TOOLTIP}> (auto)</span>
        )}
        {' '}
        <span
          className={`badge badge-${inst.mode === 'fetch' ? 'ssr-url' : inst.mode}`}
          title={MODE_TOOLTIPS[inst.mode] ?? inst.mode}
          style={{ marginLeft: 4, verticalAlign: 'middle' }}
        >
          {inst.mode}
        </span>
        <small style={{ color: '#888', fontWeight: 400, marginLeft: 8 }}>· {inst.id}</small>
        <small className="lifetime" title="Time since mount, or total lifetime if unmounted">
          {lifetime}
        </small>
      </h2>
      <h3 title="Snapshot of the instance — what mode it is, current status, mount/unmount timestamps, optional URL (for SSR), and Shadow DOM flag.">Info</h3>
      <pre>{JSON.stringify({
        pkg: inst.pkg,
        mode: inst.mode,
        status: inst.status,
        url: inst.url,
        shadowDom: inst.shadowDom,
        mountedAt: new Date(inst.mountedAt).toISOString(),
        unmountedAt: inst.unmountedAt ? new Date(inst.unmountedAt).toISOString() : undefined,
      }, null, 2)}</pre>
      {inst.lastProps !== undefined && (
        <>
          <h3 title="The most recent props the host passed to the remote — either at mount or via a propsChanged update.">Last props</h3>
          <pre>{safeStringify(inst.lastProps)}</pre>
        </>
      )}
      <h3>
        Event log ({filteredEvents.length}
        {filteredEvents.length !== inst.events.length && ` of ${inst.events.length}`})
        {/* Only show the per-kind summary in the header when there's more than
            one kind — otherwise it just repeats "(N)" in different words. */}
        {Object.keys(kindCounts).length > 1 && eventBreakdown && (
          <small className="event-breakdown" title="Events on this instance, broken down by kind">
            {' '}— {eventBreakdown}
          </small>
        )}
      </h3>
      {/* Always show filter chips for any kind that exists — keeps the UI
          consistent so users always see what kinds of events are present
          and can filter them when more arrive. */}
      {inst.events.length > 0 && (
        <div
          className="event-filter"
          title="Toggle event kinds in the log below. Useful for high-traffic instances — for example, hide `props` to focus on bus events."
        >
          {ALL_KINDS.filter((k) => kindCounts[k] > 0).map((k) => (
            <label
              key={k}
              className={`chip${enabledKinds.has(k) ? ' on' : ''}`}
              title={KIND_TOOLTIPS[k]}
            >
              <input
                type="checkbox"
                checked={enabledKinds.has(k)}
                onChange={() => toggleKind(k)}
              />
              {k} <span className="chip-count">{kindCounts[k]}</span>
            </label>
          ))}
        </div>
      )}
      <div>
        {filteredEvents.map((e, i) => {
          // We need the actual index in `inst.events` to compute previous props correctly.
          const realIndex = inst.events.indexOf(e)
          return (
            <EventRow
              key={i}
              ev={e}
              t0={inst.mountedAt}
              prevProps={e.kind === 'props' ? findPrevProps(inst.events, realIndex) : undefined}
            />
          )
        })}
      </div>
    </>
  )
}

function EventRow({
  ev, t0, prevProps,
}: { ev: MFEvent; t0: number; prevProps?: unknown }): React.JSX.Element {
  const dt = `+${(ev.ts - t0).toString().padStart(4, ' ')}ms`
  let summary: React.ReactNode
  let cls = ''
  switch (ev.kind) {
    case 'mount':
      summary = <span>{ev.mode} mount {ev.namespace ? `[${ev.namespace}]` : ''}</span>
      break
    case 'unmount':
      summary = <span>unmount</span>
      break
    case 'props': {
      // Show a small diff between the previous props snapshot and this one.
      // Three cases:
      //   - diff has entries → render PropsDiff
      //   - prev exists, diff empty → reference changed but values are equal
      //     (e.g. a fresh inline object/function with the same shape, common
      //     when host re-renders without memoising callbacks). Surface this
      //     so it doesn't look like the panel "lost" the change.
      //   - no prev (synthetic instance, no mount) → fall back to snapshot.
      const diff = prevProps !== undefined ? diffProps(prevProps, ev.props) : null
      if (diff && diff.length > 0) {
        summary = <PropsDiff parts={diff} />
      } else if (prevProps !== undefined && diff !== null) {
        summary = (
          <span
            className="props-noop"
            title="Host re-emitted props but every key is structurally equal to the previous snapshot. Usually means the host re-rendered with a fresh inline object or callback. Wrap callbacks in useCallback to avoid this churn."
          >
            re-emitted (reference change, no value diff) — <code>{summarizeProps(ev.props)}</code>
          </span>
        )
      } else {
        summary = <code>{summarizeProps(ev.props)}</code>
      }
      break
    }
    case 'event': {
      const out = ev.direction === 'host->remote'
      cls = out ? 'arrow-out' : 'arrow-in'
      summary = (
        <span>
          <span title={DIRECTION_TOOLTIPS[ev.direction]}>
            {out ? '→ remote' : '← host'}
          </span>{' '}
          <strong title={`Bus event type: ${ev.type}`}>{ev.type}</strong>{' '}
          {ev.payload !== undefined && <code>{summarizeProps(ev.payload)}</code>}
        </span>
      )
      break
    }
    case 'load':
      summary = (
        <span className={ev.phase === 'error' ? 'err' : ''}>
          load:{ev.phase}
          {ev.attempt !== undefined ? ` (attempt ${ev.attempt})` : ''}
          {ev.error ? ` — ${ev.error}` : ''}
        </span>
      )
      break
    case 'fetch':
      summary = (
        <span className={ev.phase === 'error' ? 'err' : ''}>
          fetch:{ev.phase}
          {ev.attempt !== undefined ? ` #${ev.attempt}` : ''}
          {ev.error ? ` — ${ev.error}` : ''}
        </span>
      )
      break
  }
  return (
    <div className="event-row">
      <span className="ts" title={`Captured at ${new Date(ev.ts).toISOString()}`}>{dt}</span>
      <span className="kind" title={KIND_TOOLTIPS[ev.kind]}>{ev.kind}</span>
      <span></span>
      <span className={cls}>{summary}</span>
    </div>
  )
}

function summarizeProps(p: unknown): string {
  const s = safeStringify(p)
  return s.length > 80 ? s.slice(0, 77) + '…' : s
}

/**
 * Finds the props value that was active immediately before the props event
 * at `index`. That's either the most recent earlier `props` event, or the
 * `props` carried by the `mount` event if the instance hasn't streamed any
 * updates yet. Returns undefined if neither exists (synthetic instance).
 */
function findPrevProps(events: MFEvent[], index: number): unknown {
  for (let i = index - 1; i >= 0; i--) {
    const e = events[i]
    if (e.kind === 'props') return e.props
    if (e.kind === 'mount') return e.props
  }
  return undefined
}

type DiffPart =
  | { op: 'add'; key: string; value: unknown }
  | { op: 'remove'; key: string; value: unknown }
  | { op: 'change'; key: string; from: unknown; to: unknown }

function diffProps(prev: unknown, next: unknown): DiffPart[] {
  // Bail if either side isn't a plain object — fall back to the full snapshot.
  if (!isPlainObject(prev) || !isPlainObject(next)) return []
  const parts: DiffPart[] = []
  const keys = new Set([...Object.keys(prev), ...Object.keys(next)])
  for (const key of keys) {
    const a = prev[key]
    const b = next[key]
    const inPrev = key in prev
    const inNext = key in next
    if (inPrev && !inNext) parts.push({ op: 'remove', key, value: a })
    else if (!inPrev && inNext) parts.push({ op: 'add', key, value: b })
    else if (!structuralEqual(a, b)) parts.push({ op: 'change', key, from: a, to: b })
  }
  return parts
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

/** Cheap deep-equal good enough for serialised props — uses JSON. */
function structuralEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true
  try { return JSON.stringify(a) === JSON.stringify(b) } catch { return false }
}

function PropsDiff({ parts }: { parts: DiffPart[] }): React.JSX.Element {
  return (
    <span className="props-diff">
      {parts.map((p, i) => (
        <span key={i} className={`diff-${p.op}`} title={DIFF_OP_TOOLTIPS[p.op]}>
          {i > 0 && ' '}
          <span className="diff-op">
            {p.op === 'add' ? '+' : p.op === 'remove' ? '−' : '~'}
          </span>
          {' '}
          <code>{p.key}</code>
          {p.op === 'change' ? (
            <>
              : <code>{summarizeValue(p.from)}</code> → <code>{summarizeValue(p.to)}</code>
            </>
          ) : (
            <>: <code>{summarizeValue(p.value)}</code></>
          )}
        </span>
      ))}
    </span>
  )
}

function summarizeValue(v: unknown): string {
  if (v === undefined) return 'undefined'
  if (v === null) return 'null'
  if (typeof v === 'string') return JSON.stringify(v).length > 30
    ? JSON.stringify(v).slice(0, 27) + '…"'
    : JSON.stringify(v)
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) return `[${v.length}]`
  if (typeof v === 'string' && v.startsWith('[Function')) return v
  if (isPlainObject(v)) {
    const keys = Object.keys(v)
    return keys.length === 0 ? '{}' : `{${keys.length} keys}`
  }
  return String(v)
}

function safeStringify(v: unknown): string {
  try { return JSON.stringify(v, null, 2) } catch { return String(v) }
}

function truncate(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1) + '…'
}

/**
 * Toggles a `flashing` flag for ~600ms whenever the given key (event count
 * or last-event ts) changes — used to briefly highlight a list row when
 * a new event arrives on its instance.
 */
function useFlashOnEvent(eventCount: number, lastTs: number | undefined): boolean {
  const [flashing, setFlashing] = useState(false)
  const lastSeenRef = useState({ count: eventCount, ts: lastTs })[0]
  useEffect(() => {
    if (eventCount === lastSeenRef.count && lastTs === lastSeenRef.ts) return
    lastSeenRef.count = eventCount
    lastSeenRef.ts = lastTs
    setFlashing(true)
    const id = setTimeout(() => setFlashing(false), 600)
    return () => clearTimeout(id)
  }, [eventCount, lastTs, lastSeenRef])
  return flashing
}

/**
 * Live "alive 12s" / "was alive 1m 23s" string for an instance. Re-renders
 * once a second while the instance is mounted; a frozen value once unmounted.
 */
function useLifetime(inst: Instance): string {
  const [, tick] = useState(0)
  useEffect(() => {
    if (inst.status === 'unmounted') return
    const id = setInterval(() => tick((n) => n + 1), 1000)
    return () => clearInterval(id)
  }, [inst.id, inst.status])

  if (inst.unmountedAt) {
    return `was alive ${formatDuration(inst.unmountedAt - inst.mountedAt)}`
  }
  return `alive ${formatDuration(Date.now() - inst.mountedAt)}`
}

function formatDuration(ms: number): string {
  if (ms < 0) ms = 0
  if (ms < 1000) return `${ms}ms`
  const s = Math.floor(ms / 1000)
  if (s < 60) return `${s}s`
  const m = Math.floor(s / 60)
  const rs = s % 60
  return rs === 0 ? `${m}m` : `${m}m ${rs}s`
}

/**
 * Trigger a browser download of a JSON dump of the captured instances and
 * their event logs. Filename includes a timestamp so multiple exports don't
 * overwrite each other.
 */
function exportEventsJson(items: Instance[]): void {
  const payload = {
    exportedAt: new Date().toISOString(),
    instanceCount: items.length,
    instances: items.map((i) => ({
      id: i.id,
      pkg: i.pkg,
      namespace: i.namespace,
      mode: i.mode,
      status: i.status,
      url: i.url,
      shadowDom: i.shadowDom,
      mountedAt: new Date(i.mountedAt).toISOString(),
      unmountedAt: i.unmountedAt ? new Date(i.unmountedAt).toISOString() : undefined,
      lastProps: i.lastProps,
      events: i.events,
    })),
  }
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `mf-devtools-events-${new Date().toISOString().replace(/[:.]/g, '-')}.json`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function summarizeEventKinds(events: MFEvent[]): string {
  if (events.length === 0) return ''
  const counts: Record<string, number> = {}
  for (const e of events) counts[e.kind] = (counts[e.kind] ?? 0) + 1
  // Show in protocol order so the line reads consistently.
  const order: Array<MFEvent['kind']> = ['mount', 'unmount', 'props', 'event', 'load', 'fetch']
  return order
    .filter((k) => counts[k])
    .map((k) => `${counts[k]} ${k}`)
    .join(' · ')
}

/**
 * While paused, buffer incoming events and drain them on resume so the panel
 * doesn't drop activity that happens during inspection.
 */
function useBufferedPause(
  paused: boolean,
  dispatch: React.Dispatch<Action>,
): { current: boolean; buffer: MFEvent[] } {
  const ref = useMemo(() => ({ current: paused, buffer: [] as MFEvent[] }), [])
  ref.current = paused
  useEffect(() => {
    if (!paused && ref.buffer.length > 0) {
      const flushed = ref.buffer
      ref.buffer = []
      dispatch({ type: 'events', events: flushed })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [paused])
  return ref
}

// Re-export reducer for any future test harness.
export { reduce }
