import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { SpritePluginOptions } from '../types.js';
import { analyzeImports } from '../analyzer/analyze-imports.js';
import { buildSprite } from './build-sprite.js';

export interface SpriteManifest {
  generatedAt: string;
  iconsCount: number;
  missingCount: number;
  /** Total byte size of all <symbol> elements after optimization */
  totalSizeBytes: number;
  icons: {
    name: string;
    sources: string[];
    /** Byte size of the original SVG file */
    originalBytes: number;
    /** Byte size of the <symbol> element after SVGO optimization */
    sizeBytes: number;
  }[];
  missing: string[];
}

/**
 * Main entry point: analyzes source code for icon usage,
 * builds an optimized SVG sprite, and writes the output file.
 */
export async function generateSprite(options: SpritePluginOptions): Promise<void> {
  const {
    iconsDir,
    sourceDirs,
    importPattern,
    output,
    extractNamedImports,
    extensions,
    verbose = false,
    skipIfEmpty = false,
    manifest: writeManifest = false,
    parser,
  } = options;

  // Step 1: Find which icons are used in source code
  const usages = await analyzeImports({
    sourceDirs,
    importPattern,
    extractNamedImports,
    extensions,
    parser,
  });

  const iconNames = usages.map((u) => u.name);

  if (iconNames.length === 0) {
    if (verbose) {
      console.log('[sprite] No icon imports found');
    }
    if (skipIfEmpty) return;
  }

  if (verbose) {
    console.log(`[sprite] Found ${iconNames.length} unique icons:`);
    for (const usage of usages) {
      console.log(`  ${usage.name} ← ${usage.source}:${usage.line}`);
    }
  }

  // Step 2: Build the sprite from matched SVG files
  const { svg, included, missing, sizes } = await buildSprite(iconsDir, iconNames, verbose);

  if (missing.length > 0) {
    console.warn(`[sprite] Missing icons: ${missing.join(', ')}`);
  }

  // Step 3: Write output file
  await mkdir(dirname(output), { recursive: true });

  const outputContent = generateOutputFile(svg, included);
  await writeFile(output, outputContent, 'utf-8');

  // Step 4: Write manifest JSON (optional, next to the sprite file)
  if (writeManifest) {
    const totalSizeBytes = included.reduce((sum, name) => sum + (sizes.get(name)?.sizeBytes ?? 0), 0);

    const manifest: SpriteManifest = {
      generatedAt: new Date().toISOString(),
      iconsCount: included.length,
      missingCount: missing.length,
      totalSizeBytes,
      icons: included.map((name) => {
        const size = sizes.get(name);
        return {
          name,
          sources: usages
            .filter((u) => {
              const uLower = u.name.toLowerCase();
              const nLower = name.toLowerCase();
              return uLower === nLower || uLower.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase() === nLower;
            })
            .map((u) => `${u.source}:${u.line}`),
          originalBytes: size?.originalBytes ?? 0,
          sizeBytes: size?.sizeBytes ?? 0,
        };
      }),
      missing,
    };

    const manifestPath = join(dirname(output), 'sprite-manifest.json');
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');

    if (verbose) {
      console.log(`[sprite] Manifest: ${manifestPath}`);
    }
  }

  if (verbose) {
    console.log(`[sprite] Written to ${output} (${included.length} icons)`);
  }
}

/**
 * Generates a TypeScript module that injects the sprite into the DOM at runtime.
 */
function generateOutputFile(svg: string, icons: string[]): string {
  // Escape backticks and backslashes to prevent breaking template literals
  const escapedSvg = svg.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  return `// Auto-generated by @mf-toolkit/sprite-plugin
// Icons: ${icons.join(', ')}
// Do not edit manually.

const SPRITE = \`${escapedSvg}\`;

let injected = false;

export function injectSprite(): void {
  if (injected || typeof document === 'undefined') return;
  injected = true;

  const container = document.createElement('div');
  container.style.display = 'none';
  container.setAttribute('data-mf-sprite', '');
  container.innerHTML = SPRITE;
  document.body.prepend(container);
}

export const spriteIcons = ${JSON.stringify(icons)} as const;
`;
}
