import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { SpritePluginOptions } from '../types.js';
import { analyzeImports } from '../analyzer/analyze-imports.js';
import { buildSprite } from './build-sprite.js';

/**
 * Main entry point: analyzes source code for icon usage,
 * builds an optimized SVG sprite, and writes the output file.
 */
export async function generateSprite(options: SpritePluginOptions): Promise<void> {
  const {
    iconsDir,
    sourceDirs,
    importPattern,
    output,
    extractNamedImports,
    extensions,
    verbose = false,
    skipIfEmpty = false,
  } = options;

  // Step 1: Find which icons are used in source code
  const usages = await analyzeImports({
    sourceDirs,
    importPattern,
    extractNamedImports,
    extensions,
  });

  const iconNames = usages.map((u) => u.name);

  if (iconNames.length === 0) {
    if (verbose) {
      console.log('[sprite] No icon imports found');
    }
    if (skipIfEmpty) return;
  }

  if (verbose) {
    console.log(`[sprite] Found ${iconNames.length} unique icons:`);
    for (const usage of usages) {
      console.log(`  ${usage.name} ← ${usage.source}:${usage.line}`);
    }
  }

  // Step 2: Build the sprite from matched SVG files
  const { svg, included, missing } = await buildSprite(iconsDir, iconNames, verbose);

  if (missing.length > 0) {
    console.warn(`[sprite] Missing icons: ${missing.join(', ')}`);
  }

  // Step 3: Write output file
  await mkdir(dirname(output), { recursive: true });

  const outputContent = generateOutputFile(svg, included);
  await writeFile(output, outputContent, 'utf-8');

  if (verbose) {
    console.log(`[sprite] Written to ${output} (${included.length} icons)`);
  }
}

/**
 * Generates a TypeScript module that injects the sprite into the DOM at runtime.
 */
function generateOutputFile(svg: string, icons: string[]): string {
  // Escape backticks and backslashes to prevent breaking template literals
  const escapedSvg = svg.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  return `// Auto-generated by @mf-toolkit/sprite-plugin
// Icons: ${icons.join(', ')}
// Do not edit manually.

const SPRITE = \`${escapedSvg}\`;

let injected = false;

export function injectSprite(): void {
  if (injected || typeof document === 'undefined') return;
  injected = true;

  const container = document.createElement('div');
  container.style.display = 'none';
  container.setAttribute('data-mf-sprite', '');
  container.innerHTML = SPRITE;
  document.body.prepend(container);
}

export const spriteIcons = ${JSON.stringify(icons)} as const;
`;
}
