import { describe, it, expect, afterEach } from 'vitest';
import { join } from 'node:path';
import { readFile, rm } from 'node:fs/promises';
import { generateSprite } from '../src/generator/generate-sprite.js';

const FIXTURES = join(import.meta.dirname, 'fixtures');
const OUTPUT_DIR = join(import.meta.dirname, 'fixtures/output');
const OUTPUT_FILE = join(OUTPUT_DIR, 'sprite.ts');

afterEach(async () => {
  await rm(OUTPUT_DIR, { recursive: true, force: true });
});

describe('generateSprite', () => {
  it('generates a TypeScript sprite file', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
    });

    const content = await readFile(OUTPUT_FILE, 'utf-8');
    expect(content).toContain('Auto-generated by @mf-toolkit/sprite-plugin');
    expect(content).toContain('injectSprite');
    expect(content).toContain('spriteIcons');
    expect(content).toContain('<symbol');
  });

  it('includes only used icons', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      extensions: ['.tsx'], // only app.tsx — uses cart and search
    });

    const content = await readFile(OUTPUT_FILE, 'utf-8');
    expect(content).toContain('"cart"');
    expect(content).toContain('"search"');
  });

  it('creates output directory if not exists', async () => {
    const deepOutput = join(OUTPUT_DIR, 'deep/nested/sprite.ts');

    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: deepOutput,
      extensions: ['.tsx'],
    });

    const content = await readFile(deepOutput, 'utf-8');
    expect(content).toContain('injectSprite');
  });

  it('skips generation when no icons found and skipIfEmpty is true', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: ['/nonexistent'],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      skipIfEmpty: true,
    });

    await expect(readFile(OUTPUT_FILE, 'utf-8')).rejects.toThrow();
  });

  it('generates valid JavaScript when output is written', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      extensions: ['.tsx'],
    });

    const content = await readFile(OUTPUT_FILE, 'utf-8');
    // Should not have unescaped backticks or template literal issues
    expect(content).toContain('const SPRITE = `');
    expect(content).toContain('`;');
  });

  it('exports spriteIcons as a typed array', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      extensions: ['.tsx'],
    });

    const content = await readFile(OUTPUT_FILE, 'utf-8');
    expect(content).toContain('as const');
    expect(content).toMatch(/export const spriteIcons = \[/);
  });

  it('includes SSR guard in generated code', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      extensions: ['.tsx'],
    });

    const content = await readFile(OUTPUT_FILE, 'utf-8');
    expect(content).toContain("typeof document === 'undefined'");
  });

  it('prevents double injection in generated code', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      extensions: ['.tsx'],
    });

    const content = await readFile(OUTPUT_FILE, 'utf-8');
    expect(content).toContain('let injected = false');
    expect(content).toContain('injected = true');
  });

  it('generates a sprite-manifest.json when manifest option is enabled', async () => {
    await generateSprite({
      iconsDir: join(FIXTURES, 'icons'),
      sourceDirs: [join(FIXTURES, 'src')],
      importPattern: /@my-ui\/icons\/(.+)/,
      output: OUTPUT_FILE,
      extensions: ['.tsx'],
      manifest: true,
    });

    const manifestPath = join(OUTPUT_DIR, 'sprite-manifest.json');
    const raw = await readFile(manifestPath, 'utf-8');
    const manifest = JSON.parse(raw);

    expect(manifest.iconsCount).toBeGreaterThan(0);
    expect(manifest.generatedAt).toBeDefined();
    expect(manifest.icons).toBeInstanceOf(Array);
    expect(manifest.icons.length).toBe(manifest.iconsCount);
    expect(manifest.missing).toBeInstanceOf(Array);
    expect(typeof manifest.totalSizeBytes).toBe('number');
    expect(manifest.totalSizeBytes).toBeGreaterThan(0);
    expect(typeof manifest.icons[0].sizeBytes).toBe('number');
    expect(typeof manifest.icons[0].originalBytes).toBe('number');
    expect(manifest.icons[0].originalBytes).toBeGreaterThanOrEqual(manifest.icons[0].sizeBytes);
  });
});
